name: CI Pipeline

on:
  push:
    branches:
      - master  # Replace with 'main' if your default branch is 'main'
  pull_request:
    branches:
      - master  # Replace with 'main' if your default branch is 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Use the Python version your project requires

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements/base.txt

      - name: Run tests
        run: |
          python manage.py test